name: Autograding Test

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-test:
    runs-on: ubuntu-latest
    steps:
    - name: Test code
      id: test-code
      uses: education/autograding-command-grader@v1
      with:
        test-name: 'Test 1'
        command: pytest test_main.py::test_root
        timeout: 10
        max-score: 20
        
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-CODE_RESULTS: "${{steps.test-code.outputs.result}}"
      with:
        runners: test-code