name: Autograding Test

on:
  push:
    branches: [ "main" ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-test:
    runs-on: ubuntu-latest
    steps:
    - name: Test root
      id: test-root
      uses: education/autograding-command-grader@v1
      with:
        test-name: 'Test Root'
        setup-command: sudo -H pip3 install -r requirements.txt
        command: pytest test_main.py::test_root
        timeout: 10
        max-score: 2
      
    - name: Test ids
      id: test-ids
      uses: education/autograding-command-grader@v1
      with:
        test-name: 'Test ids'
        setup-command: sudo -H pip3 install -r requirements.txt
        command: pytest test_main.py::test_ids
        timeout: 10
        max-score: 3
        
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-CODE_RESULTS: "${{steps.test-code.outputs.result}}"
      with:
        runners: test-code